This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./Template.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Template.acn....done (114 entries accepted, 0 rejected).
Sorting entries....done (814 comparisons).
Generating output file Template.acr....done (81 lines written, 0 warnings).
Output written in Template.acr.
Transcript written in Template.alg.
